### ISSUE TITLE
y-scale-slider: vertical appearance, horizontal behavior

### ISSUE THREAD

**Issue by DCLukas** [ConfusionFlow/confusionflow#4]
The `y-scale-slider` (type: `range`) has been rotated, but the slider button itself still moves horizontally, giving it a rather odd appearance. Apparent immediately upon page load of demo application. Additionally, the slider button is largely concealed by `conf-matrix-wrapper` when in default position.

**Screenshots**
![slider](https://user-images.githubusercontent.com/25404900/47004255-6f8e4e80-d131-11e8-9f45-5e5906a57ab4.png)

![slider_concealed](https://user-images.githubusercontent.com/25404900/47004782-97ca7d00-d132-11e8-9afe-27d868d46b55.png)

**System:**
Firefox 62.0.3 (64-bit)
Ubuntu 18.04.1 LTS
Extensions: uBlock Origin (0% blocked on confusionflow page)

**Comment by DCLukas** [comment]
This error was replicated in a locally (pip-)installed version, using the same system \& browser parameters.

**Comment by gfrogat** [comment]
I'm sorry, but we currently only support Google Chrome but are currently working on adding support for Firefox.

We added a popup with information about supported browser in the latest release `v0.1.2`. The container of the web demo still uses `v0.1.1` and was updated to the latest release just now.

Which version of confusionflow are you running locally? With `v0.1.2` you should get a popup like this:
![image](https://user-images.githubusercontent.com/11089303/47010857-9011d500-d140-11e8-9ea7-9447059e6921.png)

**Comment by gfrogat** [comment]
Was fixed in the frontend, I'm working on the new release of the Python package. Should be available later today from PyPI.
